'openpsa2' => array
(
     'name' => 'openpsa2',
     'title' => 'OpenPSA 2',
     'examples' => array
     (
         'http://localhost/openpsa2/',
     ),
     'root' => array
     (
         'name' => 'openpsa_root',
         'title' => 'OpenPSA',
         'component' => 'org.openpsa.mypage',
         'style' => '/template_OpenPsa2',
         'style_inherit' => true,
         'parameters' => array(),
         'acl' => array(),
         'nodes' => array
         (
             'calendar' => array
             (
                 'name' => 'calendar',
                 'title' => 'Calendar',
                 'component' => 'org.openpsa.calendar',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'contacts' => array
             (
                 'name' => 'contacts',
                 'title' => 'Contacts',
                 'component' => 'org.openpsa.contacts',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'documents' => array
             (
                 'name' => 'documents',
                 'title' => 'Documents',
                 'component' => 'org.openpsa.documents',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'expenses' => array
             (
                 'name' => 'expenses',
                 'title' => 'Expenses',
                 'component' => 'org.openpsa.expenses',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'invoices' => array
             (
                 'name' => 'invoices',
                 'title' => 'Invoices',
                 'component' => 'org.openpsa.invoices',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'products' => array
             (
                 'name' => 'products',
                 'title' => 'Products',
                 'component' => 'org.openpsa.products',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'projects' => array
             (
                 'name' => 'projects',
                 'title' => 'Projects',
                 'component' => 'org.openpsa.projects',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'reports' => array
             (
                 'name' => 'reports',
                 'title' => 'Reports',
                 'component' => 'org.openpsa.reports',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'sales' => array
             (
                 'name' => 'sales',
                 'title' => 'Sales',
                 'component' => 'org.openpsa.sales',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
             'wiki' => array
             (
                 'name' => 'wiki',
                 'title' => 'Wiki',
                 'component' => 'net.nemein.wiki',
                 'style' => '',
                 'style_inherit' => false,
                 'parameters' => array(),
                 'acl' => array(),
                 'nodes' => array(),
             ),
         ),
     ),
),
